### ISSUE TITLE
Sometimes JS doesn't get loaded

### ISSUE THREAD

**Issue by Kenny2github** [InternationalScratchWiki/ScratchWikiSkin2#10]
Originally reported [here](https://en.scratch-wiki.info/wiki/Scratch_Wiki_talk:Community_Portal#glitch)

Sometimes, ResourceLoader doesn't load content.

**Comment by apple502j** [comment]
I have this problem in jawiki, too.
Sometimes Google Analytic causes it.

**Comment by Kenny2github** [comment]
Should be fixed in [`a66166c`](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/commit/a66166c09ef6f8ad3f4a367d803f6fb6b388462c)
