### ISSUE TITLE
mediawiki.skinning.interface module to be removed in 1.40

### ISSUE THREAD

**Issue by jdlrobson** [InternationalScratchWiki/ScratchWikiSkin2#109]
Migration instructions are available here:
https://www.mediawiki.org/wiki/Manual:ResourceLoaderSkinModule#For_skins_deprecating_the_legacy_feature

Inaction may result in a change in appearance for your skin in 1.39.
For more information/concerns: https://phabricator.wikimedia.org/T317993

**Comment by Kenny2github** [comment]
Thanks for reporting this.
