### ISSUE TITLE
Delete flags from wiki logos & update the logo

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/ScratchWikiSkin2#113]
This [issue](https://github.com/InternationalScratchWiki/scratch-wiki.info/issues/11) made me realize **we will, at some point, "have to" create logos for all those tests wikis**.

This is not something that's sustainable in the long run and it will also accentuate the problems regarding flags we're having (keep reading to know more).

## Deleting the flag from the logo

**Flags are meant to represent territories**, regardless of their size.
It can range from a continent, to a group of countries, a single country, a state, a region, a town or even a neighborhood.

**The wikis are all about Scratch in a specific language**, not Scratch in a specific area.

Even tho the names of most languages do come from the name of the place they are from, areas and languages do not map/overlap very well.

- **Some countries might have multiple official and unofficial languages**, at the national and the regional level!
  - Belgium has 3 national languages (Dutch, French, and German). Notice how the Belgian flag doesn't appear on the German-speaking Scratch wiki. 🤔
  - Luxemburg has 3 (Luxembourgish, French, and German).
  - Switzerland has 4 (German, French, Italian and Romansh).
  - etc.
  - Most countries in Africa have more than one national language, and plenty of regional languages.
  - Basically, just have a look at [this](https://en.wikipedia.org/wiki/List_of_multilingual_countries_and_regions).

So what about countries with multiple languages? Do we put the same flag of that country for each of the languages that are spoken there?
Like, if we had a Scratch Wiki in both traditional and simplified Chinese, would the two wikis both have the flag of China?
Wouldn't that be confusing people trying to find the right wiki just by looking at the flag? "It's the same flag, why are two wikis?"

Likewise, **a single language can be spoken in lots of different countries**:
- English is the official language [in 58 countries](https://en.wikipedia.org/wiki/List_of_countries_and_territories_where_English_is_an_official_language).
- same with French and [its 29 countries](https://en.wikipedia.org/wiki/List_of_countries_and_territories_where_French_is_an_official_language)
- same with Spanish, Arabic, Russian, Portuguese, etc.

It raises the following question: Should we put the flag of all of these 58/29/etc countries? No, that's not possible, right?

Should we just put one flag then? Maybe. Which one then? The flag of the country the language comes from?

So what if we put the union jack on the English-speaking wiki? Wouldn't that trigger all the americans? Iirc that was the exact reason why we didn't add any flag on the logo of the English-speaking wiki. And why the union jack? That's the flag for the United Kingdom, but the wiki is not british. Should we put the flag of England then? Excluding Scotland, Wales and Northern Ireland?

Anyway, this is a problem without one good solution, so **let's get rid of the flag**.
It only causes trouble and adds little to no value.

## Updating the logo

All existing logos are based on the one from the English-speaking wiki, which was the first wiki. That logo is old.

It was "fitting" the Scratch 2.0 website style ok-ish with its darker shades, lots of details, and gradients. Something that was common with older logos using the [skeuomorphic style](https://www.google.com/search?q=Skeuomorphic).

But now we switched to the more modern ScratchWikiSkin2 skin, it looks out of place and could be improved upon.
Making it more "flat" or using a minimalist icon would imo look much better.

That would also allow to replace some of the existing logos that are quite blurry or with parts of the white background not correctly removed (looking at you Indonesian and Dutch wikis 👀). Also having SVG version would be very welcome too (supported by literally all browsers, so why not use them?).

## Final words

Anyway, all of this needs of course to be discussed with the whole Scratch Wiki community.
Those are big changes after all, I mean, kinda.

You might think we are fine with the situation as-is, and that we can just not put a flag for any new official Scratch Wiki; but it's not the case. Not putting any flag will raise questions about the wikis that do have flags. "Why do those wikis have flags and not mine / the wiki in my language?"

So yeah, I've come to that conclusion, we need to get rid of the flags, and it would be nice to have newer and slicker logos.

Thank you from coming to my Ted talk. 👍

**Comment by Kenny2github** [comment]
This is not a topic to broach in a GitHub issue, which is meant for issues with the repo it belongs to. Also, we are not changing the original logo design. The French wiki is the odd one out here.
