### ISSUE TITLE
Wikitable styling doesn't work in MW 1.39

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#116]
For this:
```html
<table class="wikitable">
...table contents...
</table>
```

These tables are showing as unstyled in MW 1.39.

**Comment by Kenny2github** [comment]
Wikitables [should still be around](https://www.mediawiki.org/wiki/Help:Tables#class=%22wikitable%22) so something else sussy is going on here...

**Comment by Kenny2github** [comment]
This is likely a duplicate of #109

**Comment by Kenny2github** [comment]
Duplicate of #109
