### ISSUE TITLE
Unexplained error in console

### ISSUE THREAD

**Issue by joker314** [InternationalScratchWiki/ScratchWikiSkin2#12]
I experience no loss of functionality, but in the developer console, the following error message is displayed.

```
ReferenceError: mwCustomEditButtons is not defined ReferenceError: mwCustomEditButtons is not defined
```

Here is an image showing the error message.

![image](https://user-images.githubusercontent.com/18113170/38157891-457d2062-3483-11e8-98c1-b72cbf394c30.png)

**Comment by Kenny2github** [comment]
This is an issue with MediaWiki:Common.js on the wiki it's on, not with the skin itself. Closing as wontfix.
