### ISSUE TITLE
Sidebar is forcing down main content on webkit-based browsers

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#126]
![image](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/assets/1960707/e08a308b-82a1-42ed-892f-675d34f0c98c)

This has been reproduced on Safari on macOS (macOS 13.5 and Safari 16.6) and other Webkit-based browsers on Linux, but does not affect Chrome or Firefox on any platform.

Credit to @dominic-03 and @GrahamSH-LLK for reporting and validating this issue.

**Comment by jacob-g** [comment]
While the two users in mentioned in the issue reported this issue, I cannot reproduce (using latest macOS and Safari) in either BrowserStack or on an actual Mac.

**Comment by GrahamSH-LLK** [comment]
> @GrahamSH-LLK reports that this also is reproducible in other Webkit-based browsers on Linux.

not me!

**Comment by gohoski** [comment]
> > @GrahamSH-LLK reports that this also is reproducible in other Webkit-based browsers on Linux.
> 
> not me!

Yeah, its me 😀 (I think)
And on Webkit from Playwright on Windows, probably also reproducible on other ordinary WebKit-browsers.

**Comment by ilikecereal1** [comment]
It’s happening on my ipad :(

**Comment by Kenny2github** [comment]
Can reproduce on macOS Ventura 13.4, Safari 16.5 (18615.2.9.11.4), investigating.
