### ISSUE TITLE
Hamburger menu not working on mobile

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#130]
Reported by ahmetlii

Steps to reproduce:
1. Open the Wiki on a mobile browser (I used Firefox Android)
2. Click the hamburger menu at the top left

Expected behavior: sidebar opens
Actual behavior: sidebar does not open (nothing happens)

**Comment by Kenny2github** [comment]
Can*not* reproduce on Chrome mobile so this seems to be browser-specific.

**Comment by jacob-g** [comment]
From MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Element/computedStyleMap
computedStyleMap is not compatible with Firefox
