### ISSUE TITLE
Login Dropdown not dropping for IE 11

### ISSUE THREAD

**Issue by LiFaytheGoblin** [InternationalScratchWiki/ScratchWikiSkin2#20]
The Scratcher Samueldora reported that the dropdown menu for logging into the German Wiki doesn't work for them. Scripts are all allowed. 
I tested on IE and it does indeed not work.
I tested on Chrome, FF and Edge and it works fine.

**Comment by LiFaytheGoblin** [comment]
Didn't see any!

**Comment by LiFaytheGoblin** [comment]
That is I didn't find how to open the console in IE ._.

**Comment by apple502j** [comment]
@LiFaytheGoblin Press F12 to open console :grinning:

**Comment by apple502j** [comment]
Working at my WIndows 10 64bit, IE 11
But IE does not have HTMLElement.onmouseout either... :-1:

**Comment by Kenny2github** [comment]
@LiFaytheGoblin does it work for your case now?

**Comment by LiFaytheGoblin** [comment]
It does @Kenny2github! Awesome!
