### ISSUE TITLE
Edit footer to fix some legal issues

### ISSUE THREAD

**Issue by LiFaytheGoblin** [InternationalScratchWiki/ScratchWikiSkin2#21]
The footer of the skin should be removed since the links might be confusing and even lead to dangerous confusion (eg all about privacy). 
This was talked about in the Scratch Club meeting of June 4. 2019

**Comment by Kenny2github** [comment]
This is a much more major change than you think. The whole point of the SWS is to look like the Scratch website; removing the footer would surprise people rather than helping with their confusion. Perhaps it should be made clearer that the Wiki's footer is under the content box, while Scratch's footer is at the bottom of the page, but removing the footer isn't really an option.

**Comment by LiFaytheGoblin** [comment]
Well, both Will and I think so. Especially the Urheberrecht needs to be removed for legal reasons (that's the whole stuff about privacy). Since we are not the Scratch website but in this case act as if these were our legal pages. Maybe just remove that for now and we somehow find a compromise for the other points? 
Like for "jobs" or "credits" people could also think it's for the wiki not Scratch.

About the similarity of the sites: We practically had only applications recently from users who thought they were requesting an account for the Scratch website, not for the wiki... So not sure... Just a though I wanted to share.

Thanks for all the work!

**Comment by Kenny2github** [comment]
Perhaps prepending the word "Scratch" to any sensitive links would help? I.e. instead of "Privacy Policy", "Terms and Conditions", "Jobs", etc. it would be "Scratch Privacy Policy", "Scratch Terms and Conditions", "Scratch Jobs". That should do away with the ambiguity.

**Comment by LiFaytheGoblin** [comment]
To be honest I don't see why it makes sense to have these links there. I mean couldn't we replace them to the wiki equivalents of these pages?

**Comment by Kenny2github** [comment]
I don't see why it makes sense to remove them. I really don't think it's a good idea to remove the footer - with the navbar color change, we're already detached enough from the main site. I think prepending "Scratch" to sensitive links is the way to go.

**Comment by LiFaytheGoblin** [comment]
I think we should chat about this issue more in the next Scratch club! You did raise some valid points.

**Comment by Kenny2github** [comment]
When's the next Scratch club? ah, but it's likely when I'm asleep 🤔

**Comment by LiFaytheGoblin** [comment]
it's monday at 8 CET. I'll give them a link to this thread if you can not attend or we could try and schedule another meeting?

**Comment by Kenny2github** [comment]
Monday 8pm CEST is Tuesday 2am HKT! I have exams that week so there's no way I'm staying up that late. I think it's ok for you to discuss it without me, though, since it's hard to arrange other times. Do let me know the results; make sure to point out the strong need to look like the Scratch website.

**Comment by LiFaytheGoblin** [comment]
Urgh that's not a good time for you indeed :( I will try to explain all your points.

**Comment by apple502j** [comment]
@LiFaytheGoblin @Kenny2github How about only removing "Legal" section?

**Comment by LiFaytheGoblin** [comment]
Yep, that would be my solution of choice about that category of the footer at least.

**Comment by Kenny2github** [comment]
In that case, I'll immediately remove the Legal section. Other sensitive links can be dealt with separately.

**Comment by LiFaytheGoblin** [comment]
Thanks @Kenny2github

**Comment by LiFaytheGoblin** [comment]
So, only Wil and I were at the SC last Monday, so we postponed discussion about other links. It might be worth it starting the discussion in the community portal to maybe hear more perspectives? So far the footer looks really good :D

**Comment by LiFaytheGoblin** [comment]
Martin and I talked about this and came to the following conclusions

Links:
Credits > Rename to "Scratch Team"
Jobs > Rename to "Jobs at Scratch"
Under Community > Add "Community Portal"
FAQ > Link to Wiki Article if available
Under Support > Add "Help for Wiki Authors" with link to wiki help
Contact Us > Remove
Donate > Rename to "Donate to Scratch"
Under Scratch Family > Add "Scratch Website" with link to https://scratch.mit.edu/

The normal Wiki Footer:
![grafik](https://user-images.githubusercontent.com/5471273/41554753-0ff616c8-7336-11e8-8e04-3cfe6a3cffde.png)

Add to Scratch Wiki Footer a link to "Impressum" for ALL Wikis: "Haftungsausschluss" is not the correct word! It needs to be "Impressum" (DMCA in english). It's a link to this page: https://scratch-dach.info/wiki/Scratch-Wiki:Impressum . This is very important legally!!!

We could reintroduce the 
"Legal
    Terms of Use
    Privacy Policy
    DMCA"
section
with links to our own things (which are in the normal wiki footer at the moment, see picture).
So:
Legal
  Privacy Policy
  DMCA

And About Scratch Wiki could be under "About".

**Comment by Kenny2github** [comment]
Anything that says "Done" below is in #24
>Martin and I talked about this and came to the following conclusions
>
>Links:
>Credits > Rename to "Scratch Team"

Done.

>Jobs > Rename to "Jobs at Scratch"

I renamed it to "Scratch Jobs" instead, it's more grammatical IMO.

>Under Community > Add "Community Portal"
>FAQ > Link to Wiki Article if available

Done. The FAQ links to the same page as the header link (under "Tips").

>Under Support > Add "Help for Wiki Authors" with link to wiki help

I used the default system message for "help" instead, which in English is just "Help". Hopefully the lack of change in header color will be enough to indicate that "help" is Wiki help while "tips" is Scratch tips.

>Contact Us > Remove
>Donate > Rename to "Donate to Scratch"
>Under Scratch Family > Add "Scratch Website" with link to https://scratch.mit.edu/

Done.

>Add to Scratch Wiki Footer a link to "Impressum" for ALL Wikis: "Haftungsausschluss" is not the correct word! It needs to be "Impressum" (DMCA in english). It's a link to this page: https://scratch-dach.info/wiki/Scratch-Wiki:Impressum . This is very important legally!!!

This is not a skin issue, but I've fixed it on the dewiki by changing [the "disclaimer" system message](https://scratch-dach.info/wiki/MediaWiki:disclaimer)

>We could reintroduce the
>"Legal
>Terms of Use
>Privacy Policy
>DMCA"
>section
>with links to our own things (which are in the normal wiki footer at the moment, see picture).
>So:
>Legal
>Privacy Policy
>DMCA
>
>And About Scratch Wiki could be under "About".

All done.
