### ISSUE TITLE
Some Wikis still have old skin

### ISSUE THREAD

**Issue by LiFaytheGoblin** [InternationalScratchWiki/ScratchWikiSkin2#23]
https://www.scratch-indo.info/wiki/Halaman_Utama
https://nl.scratch-wiki.info/wiki/Hoofdpagina
https://scratch-ru.info/wiki/%d0%97%d0%b0%d0%b3%d0%bb%d0%b0%d0%b2%d0%bd%d0%b0%d1%8f_%d1%81%d1%82%d1%80%d0%b0%d0%bd%d0%b8%d1%86%d0%b0
https://hu.scratch-wiki.info/wiki/Kezd%c5%91lap

**Comment by Kenny2github** [comment]
This is because we are waiting for the OK from those wikis to implement the new skin before actually using it - a skin change is a major design change and we need to make sure that the language communities are OK with it.

**Comment by LiFaytheGoblin** [comment]
I see... I wonder if there is anything we can do to get on the safe side legally and still give the communities time?

**Comment by Kenny2github** [comment]
I think the only thing that can be done is to directly edit the old skin itself. But more wikis seem to be becoming more active lately - I have a comment on my profile that seems to be about implementing the new skin on the Russian wiki, and I've asked Rumanti if the indo wiki wants it. We'll see how it goes, though

**Comment by LiFaytheGoblin** [comment]
Thanks!
