### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by dimon4ezzz** [InternationalScratchWiki/ScratchWikiSkin2#34]
Just watch image: https://scratch-ru.info/w/images/e/e0/Скриншот1.jpg

In common: search box is very small. Please, use scalable design in css. [Google what is scalable design](https://google.com/search?q=css%20scalable%20design)

**Comment by Kenny2github** [comment]
If you manage to click into the search box, you'll find that it expands to cover the rest of the header. If you want scalable design, ask for it on Scratch first - this skin mimics the Scratch website as much as possible.
