### ISSUE TITLE
"Helvetica Neue" displays strangely in some browsers

### ISSUE THREAD

**Issue by Kenny2github** [InternationalScratchWiki/ScratchWikiSkin2#4]
Originally reported [here](https://en.scratch-wiki.info/wiki/Scratch_Wiki_talk:Community_Portal#Some_things...).

For some users, the indented text (which is actually a `<dl><dd>indented text</dd></dl>`) is showing up in a different font. It turns out that Helvetica Neue acts strangely on some browsers (seemingly [specifically on Windows 7](https://superuser.com/questions/1006331/why-does-helvetica-neue-render-poorly-on-my-windows-7-latest-version-of-chrom)). If there's a way to fix this issue server-side, great. If not, what font should be used instead? Something as close as possible to the Scratch site's font would be preferable - we would like to stay as close to the Scratch site's styling as we can.

**Comment by Smrman** [comment]
It's a client-side bug. The font may be displayed strangely if corrupt. Try uninstalling and installing the font back to solve the problem. (As shown in [this video](https://www.youtube.com/watch?v=UfgQX_rZ5YQ).)

Another solution would be to change the font to something simmilar as you said, so [Liberation Sans](https://www.dafont.com/liberation-sans.font) would be the closest one (See [here](https://graphicdesign.stackexchange.com/questions/15462/is-there-a-free-helvetica-neue-alternative)) .

**Comment by Kenny2github** [comment]
Should be resolved by [`01f6033`](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/commit/01f603334f756b6c6ef0361b61e82d39c8dfe965)
