### ISSUE TITLE
Table makes page overflow on the right

### ISSUE THREAD

**Issue by Smrman** [InternationalScratchWiki/ScratchWikiSkin2#43]
Here we go again,

Same problem than [Issue#42](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/issues/42)

On a small screen, when there is a WikiTable (table) in the page, it sometimes overflows on the right side, leaving a huge scrollable blank space.

See below (Google Chrome mobile device emulator)
Taken from [FlashPlayer/bugs on Fr Scratch Wiki](https://fr.scratch-wiki.info/wiki/Flash_Player/bugs).
![image](https://user-images.githubusercontent.com/17651422/45754292-91241500-bc1b-11e8-81ba-1fd434c42b6e.png)

Could be solved by setting table as flex when on mobile.
Just one line of CSS is needed and it works...
```css
table {
display: flex;
}
```

**Comment by Kenny2github** [comment]
`display: flex` does this:
![image](https://user-images.githubusercontent.com/28599280/45755243-8041c680-bc50-11e8-8021-acc0a42fce14.png)
And this is not an issue I intend to fix. Tables sometimes even overflow on desktop! There is no good fix for it. Only solution is to allow scrolling of the content box itself, which I have already done. Closing as wontfix.

**Comment by Smrman** [comment]
Oh, forgot to mention,

you also have to add
```css
overflow-x: scroll;
```

and it looks good ;)
![image](https://user-images.githubusercontent.com/17651422/45755411-a8183680-bc1e-11e8-9cff-0e573e3da3c6.png)
