### ISSUE TITLE
Use CSS media query for dark theme

### ISSUE THREAD

**Issue by Ascor8522** [InternationalScratchWiki/ScratchWikiSkin2#58]
While having a setting to enable or disable the dark theme is a good idea,
it would also be nice to have a "system-like" option, wich sets the theme to whatever the system theme is (light or dark).

This can be acieved in css with the following media query

```
@media (prefers-color-scheme: dark) {

}
```

Also, it would be great to add another option to sitch dark theme on automatically depending on the user's local time.
i.e. Dark theme would be enabled from 9PM to 7AM.
The user's time could be retrieved from MW or the HTTP request.

Working on a prototype for both these ideas.

**Comment by Kenny2github** [comment]
* I don't think there is a method to get system theme
* [There is already a JS media query used](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/dark-theme/ScratchWikiSkinTemplate.php#L257-L259) to get the *browser* theme setting
* Dark theme depending on time isn't something I plan on supporting, as that can be done with userscripts if people find it that useful.
