### ISSUE TITLE
Deprecated: SkinScratchWikiSkin::setupSkinUserCss must not modify the style module list,

### ISSUE THREAD

**Issue by jdlrobson** [InternationalScratchWiki/ScratchWikiSkin2#72]
In MediaWiki (current master):

`( ! ) Deprecated: SkinScratchWikiSkin::setupSkinUserCss must not modify the style module list, this is deprecated since 1.32 [Called from OutputPage::getRlClient in /vagrant/mediawiki/includes/OutputPage.php at line 2996] in /vagrant/mediawiki/includes/debug/MWDebug.php on line 329`

You can move the body of the `setupSkinUserCss` into `initPage` to safely fix this.

**Comment by Kenny2github** [comment]
@jacob-g Assigning you in case you feel like fixing this, I'm otherwise entangled at the moment

**Comment by jacob-g** [comment]
Will investigate when I get the chance. Thanks for the heads up.
