### ISSUE TITLE
Is it possible to customize logo in header and the links in the footer?

### ISSUE THREAD

**Issue by jdlrobson** [InternationalScratchWiki/ScratchWikiSkin2#75]
Could the readme be updated with instructions on how to customize the logo in the header (it doesn't use the `wordmark` I've defined in https://www.mediawiki.org/wiki/Manual:$wgLogos)

<img width="651" alt="Screen Shot 2021-01-03 at 10 50 06 AM" src="https://user-images.githubusercontent.com/148752/103486268-7278c680-4db1-11eb-951f-82bdb287555e.png">

As for the footer, I'd like to disable this or replace the links. Is there a MediaWiki page that can be used to do that?

<img width="696" alt="Screen Shot 2021-01-03 at 10 58 10 AM" src="https://user-images.githubusercontent.com/148752/103486412-94267d80-4db2-11eb-9c20-1ac3951d8df6.png">

**Comment by Kenny2github** [comment]
The logo in the header is *not* `$wgLogo` (which controls the logo just below it) and does not support customization. `$wgLogos` (plural) is not supported at all yet - I didn't know it existed until just now.
There isn't any way to disable the links, but there are [various `scratchwikiskin-footer-*` system messages](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/master/i18n/qqq.json#L30-L61) controlling their text [(though not their urls)](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/master/ScratchWikiSkinTemplate.php#L184-L227).
This skin isn't really meant to be used beyond the Scratch Wikis, and it was only on a whim that I requested live previews be enabled for it on your site. If issues like these make it un-enable-able, feel free to drop it entirely.

**Comment by jdlrobson** [comment]
I'm mostly curious for [the documentation on mediawiki.org](https://www.mediawiki.org/wiki/Skin:ScratchWikiSkin) to explain the state. If 3rd party wikis wanted to use the skin and submitted pull requests to make things more generic would you be willing to accept them, or would it be preferred that they fork the skin with a new name and adjust it themselves?

**Comment by Kenny2github** [comment]
I've [updated](https://www.mediawiki.org/w/index.php?title=Skin:ScratchWikiSkin2&diff=4325833&oldid=4325728) the documentation.
> If 3rd party wikis wanted to use the skin and submitted pull requests to make things more generic would you be willing to accept them

Possibly, but it would probably take some time to accept them since a lot of what we do is endlessly procrastinated upon.

**Comment by Ascor8522** [comment]
While we _could_ technically do it very easily, I personally don't think we should consider it/allow it.

The header with the Scratch logo and the footer with all the links **are key parts of the skin**.
In fact, there are **the main reasons** why this skin has been created, to reproduce the Scratch's website's headers and foorter.

Why should we then allow the footer to be disabled if the primary goal was to add it to the page?
Same for the logo. It's always supposed to be the Scratch's logo.

**The intent has never been to make a generic skin**, just like @Kenny2github said.
> This skin isn't really meant to be used beyond the Scratch Wikis

**Comment by jdlrobson** [comment]
Make sense. I think your skin is really interesting and provides a different aesthetic to a lot of the existing ones, but I understand maintaining generic code is hard.

In case it's of use, #78 should be all that's needed to allow other MediaWiki instances the ability to customize the logo (I won't be offended if you decline it).

Thanks for adding the note on mediawiki.org about the footer. I think that's fine guidance for now.
