### ISSUE TITLE
Add wiki Table of Contents to Explore tab

### ISSUE THREAD

**Issue by SausageMcSauce** [InternationalScratchWiki/ScratchWikiSkin2#82]
The Table of Contents page on the English wiki seems to fit the definition of 'Explore'. I am suggesting that it is added to the Explore tab on the header.

However, there might be a chance that not every Scratch Wiki in every language has a Table of Contents (Only a Russian one is mentioned in the Other Languages tab of the English Table of Contents).

**Comment by Kenny2github** [comment]
That's exactly the issue - something included in a skin used on all wikis must be usable by all wikis. I considered this when originally making the skin and didn't include it because a good number of wikis don't have it.

**Comment by R4356th** [comment]
Why not add a configuration variable so that individual wikis can request it after creating a ToC?

**Comment by Kenny2github** [comment]
Ideally the entire header would be customizable through an interface message à la [MediaWiki:Sidebar](https://en.scratch-wiki.info/wiki/MediaWiki:Sidebar) but that's a larger feature that a) I'm not sure is worth supporting yet and b) should be discussed in its own issue
