### ISSUE TITLE
Don't hotlink images from Scratch

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#90]
This can cause them to be unavailable when Scratch is down (and also runs the risk that the Scratch site may restructure its assets without telling us).

[Reported by Jammum](https://en.scratch-wiki.info/wiki/Scratch_Wiki_talk:Community_Portal#Have_a_copy_of_the_Scratch_logo_and_the_search_bar_image_on_the_Wiki.27s_servers)

**Comment by ahmetlii** [comment]
I guess that's solved, right?
