### ISSUE TITLE
Showing "not required" on search dropdown for non-logged-in users

### ISSUE THREAD

**Issue by jacob-g** [InternationalScratchWiki/ScratchWikiSkin2#97]
Issue was reported by LOLScratch12233, screenshot below (provided by aforementioned user [here](https://scratch.mit.edu/projects/596583936/)).

![7B3D0FA5-9804-4CC4-92F0-26C056DB6E2F](https://user-images.githubusercontent.com/1960707/140630926-2773eb38-12d7-4156-821e-0b071b8947e0.png)

**Comment by Kenny2github** [comment]
I find it highly unlikely that this is legitimate, considering the only part of the code that ever said "Not required" [was just recently removed](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/pull/96).

**Comment by Ascor8522** [comment]
Some (French-speaking) users also noticed it and asked me about it, tho it was not showing up on my screen (but was still there when viewing the source of the page).

**Comment by jacob-g** [comment]
I will try to reproduce this tomorrow using BrowserStack to emulate an iPad. I personally have not experienced it on Firefox on Windows or Android.

**Comment by jacob-g** [comment]
Cannot reproduce in BrowserStack:
![image](https://user-images.githubusercontent.com/1960707/140773198-f525578f-cbbb-4466-ab64-4690f1f20fe5.png)
![image](https://user-images.githubusercontent.com/1960707/140773285-ec80e302-2496-454e-a582-9ef8230003d9.png)

@Ascor8522 Do you have any screenshots from the users reporting the issue?

**Comment by jacob-g** [comment]
Reproduced in BrowserStack for iPad Safari:
![image](https://user-images.githubusercontent.com/1960707/140773631-4fd757e0-e664-4569-968e-122aa6a6be28.png)

**Comment by jacob-g** [comment]
Also reproduced in Chrome on Windows:
![image](https://user-images.githubusercontent.com/1960707/140774027-4e763a05-e191-4fdc-8ce0-1c3ed12a752c.png)

Reprioritizing as high priority

**Comment by jacob-g** [comment]
Here is the relevant section in the inspector:
![image](https://user-images.githubusercontent.com/1960707/140774186-37b002bb-e47e-42de-83eb-852c6f4ca5ed.png)

**Comment by jacob-g** [comment]
This issue only affects non-logged in users. Also removing "mobile" tag since this occurs on desktop too

**Comment by jacob-g** [comment]
As @Ascor8522 reported, this is also included in the HTML source for non-logged-in users, so it's not added after the fact with JS. I don't see where it's added by the skin, so this probably comes from some other extension monkeying with our markup?

**Comment by jacob-g** [comment]
I can't find any extensions on EN that aren't also on staging that would be remotely linked to this.

**Comment by jacob-g** [comment]
Grepping shows a bunch of cache entries, so I'll try clearing the cache

**Comment by jacob-g** [comment]
Purging the cache entry for the main page seems to fix the issue there.

**Comment by jacob-g** [comment]
Cache purged for EN and FR, that seems to fix the problem. Note that we may see some transient performance issues.

**Comment by jacob-g** [comment]
I nuked the file cache, that seems to be fixing it.

**Comment by Ascor8522** [comment]
> I don't see where it's added by the skin, so this probably comes from some other extension monkeying with our markup?

That's what I originally thought too, but it was part of the skin all along.
Maybe some recent change in the CSS made it appear.

See the initial [commit](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/commit/f4d658fc521ad265e9fe171a0e2f5c2541b4c388#diff-bf69e0537c025f796ae24efe9757aba354818e50a32460d37a361545d29c5183R42)

https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/f4d658fc521ad265e9fe171a0e2f5c2541b4c388/ScratchWikiSkinTemplate.php#L39-L43

And the [commit that removed it](https://github.com/InternationalScratchWiki/ScratchWikiSkin2/pull/96/files#diff-bf69e0537c025f796ae24efe9757aba354818e50a32460d37a361545d29c5183L84)

https://github.com/InternationalScratchWiki/ScratchWikiSkin2/blob/8e144e9a82587a39cf86cc5c878f6151da1151d8/ScratchWikiSkinTemplate.php#L83-L86

**Comment by jacob-g** [comment]
@Ascor8522 I think it was due to it being cached from before we removed that. Clearing the cache seems to have fixed it.
