### ISSUE TITLE
Skin is incompatible with VisualEditor

### ISSUE THREAD

**Issue by MacFan4000** [InternationalScratchWiki/ScratchWikiSkin2#98]
When I try to load the skin with VisualEditor installed, it is broken and in my console I see a message that the skin is not compatible with VE. I am using MediaWiki 1.37.0.

**Comment by Kenny2github** [comment]
Marking as low priority because the Scratch Wiki uses 1.35

**Comment by Kenny2github** [comment]
VE is compatible now.
